// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TGC.RegardedStonks.Infrastructure.Persistence;

#nullable disable

namespace TGC.RegardedStonks.Infrastructure.Migrations
{
    [DbContext(typeof(RegardedStonksWriteDbContext))]
    partial class RegardedStonksWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.MatchEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("StockMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("StockMatchId");

                    b.ToTable("match_events", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Oid")
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Oid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerPortfolioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PrisonReleaseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StockMatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("player_portfolios", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerStockPortfolioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerPortfolioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("StockCompanyId");

                    b.HasIndex("PlayerPortfolioId", "StockCompanyId")
                        .IsUnique();

                    b.ToTable("player_stock_portfolios", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("AvailableStocks")
                        .HasColumnType("integer");

                    b.Property<bool>("Bankrupt")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastReportedProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LastReportedRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NonLiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StockMatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("StockMatchId");

                    b.ToTable("stock_companies", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("StartingCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.ToTable("stock_matches", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockMatchPlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StockMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StockMatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("stock_match_players", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.TemplateStockCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("AvailableStocks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastReportedProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LastReportedRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NonLiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("template_stock_companies", (string)null);
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.MatchEventEntity", b =>
                {
                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", "StockMatch")
                        .WithMany("MatchEvents")
                        .HasForeignKey("StockMatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StockMatch");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerPortfolioEntity", b =>
                {
                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.PlayerEntity", "Player")
                        .WithMany("PlayerPortfolios")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", "StockMatch")
                        .WithMany("PlayerPortfolios")
                        .HasForeignKey("StockMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("StockMatch");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerStockPortfolioEntity", b =>
                {
                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.PlayerPortfolioEntity", "PlayerPortfolio")
                        .WithMany("PlayerStockPortfolios")
                        .HasForeignKey("PlayerPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.StockCompanyEntity", "StockCompany")
                        .WithMany("PlayerStockPortfolios")
                        .HasForeignKey("StockCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerPortfolio");

                    b.Navigation("StockCompany");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockCompanyEntity", b =>
                {
                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", "StockMatch")
                        .WithMany("StockCompanies")
                        .HasForeignKey("StockMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockMatch");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockMatchPlayerEntity", b =>
                {
                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.PlayerEntity", "Player")
                        .WithMany("StockMatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", "StockMatch")
                        .WithMany("StockMatchPlayers")
                        .HasForeignKey("StockMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("StockMatch");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerEntity", b =>
                {
                    b.Navigation("PlayerPortfolios");

                    b.Navigation("StockMatchPlayers");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.PlayerPortfolioEntity", b =>
                {
                    b.Navigation("PlayerStockPortfolios");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockCompanyEntity", b =>
                {
                    b.Navigation("PlayerStockPortfolios");
                });

            modelBuilder.Entity("TGC.RegardedStonks.Infrastructure.Entities.StockMatchEntity", b =>
                {
                    b.Navigation("MatchEvents");

                    b.Navigation("PlayerPortfolios");

                    b.Navigation("StockCompanies");

                    b.Navigation("StockMatchPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
