/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MatchesRequestBuilderNavigationMetadata, MatchesRequestBuilderRequestsMetadata, type MatchesRequestBuilder } from './matches/index.js';
// @ts-ignore
import { PlayersRequestBuilderNavigationMetadata, PlayersRequestBuilderRequestsMetadata, type PlayersRequestBuilder } from './players/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin
 */
export interface AdminRequestBuilder extends BaseRequestBuilder<AdminRequestBuilder> {
    /**
     * The matches property
     */
    get matches(): MatchesRequestBuilder;
    /**
     * The players property
     */
    get players(): PlayersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdminRequestBuilderUriTemplate = "{+baseurl}/api/admin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    matches: {
        requestsMetadata: MatchesRequestBuilderRequestsMetadata,
        navigationMetadata: MatchesRequestBuilderNavigationMetadata,
    },
    players: {
        requestsMetadata: PlayersRequestBuilderRequestsMetadata,
        navigationMetadata: PlayersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
