<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\TGC.Framework\src\Communication\TGC.Communication\TGC.Communication\TGC.Communication.csproj" />
      <ProjectReference Include="..\TGC.RegardedStonks.Domain\TGC.RegardedStonks.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Matches\DeleteMatch\" />
      <Folder Include="Features\MatchInvitations\GetAllMatchInvitations\" />
    </ItemGroup>

</Project>
