/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ArchiveItemRequestBuilderRequestsMetadata, type ArchiveItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/matches/archive
 */
export interface ArchiveRequestBuilder extends BaseRequestBuilder<ArchiveRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.matches.archive.item collection
     * @param id Unique identifier of the item
     * @returns {ArchiveItemRequestBuilder}
     */
     byId(id: Guid) : ArchiveItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ArchiveRequestBuilderUriTemplate = "{+baseurl}/api/matches/archive";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ArchiveRequestBuilderNavigationMetadata: Record<Exclude<keyof ArchiveRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ArchiveItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
