/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreatePlayerSelfCommandResponseFromDiscriminatorValue, createGetPlayerDetailsSelfQueryResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type CreatePlayerSelfCommandResponse, type GetPlayerDetailsSelfQueryResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type UsernameRequestBuilder, UsernameRequestBuilderRequestsMetadata } from './username/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/player/self
 */
export interface SelfRequestBuilder extends BaseRequestBuilder<SelfRequestBuilder> {
    /**
     * The username property
     */
    get username(): UsernameRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetPlayerDetailsSelfQueryResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetPlayerDetailsSelfQueryResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePlayerSelfCommandResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 409 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePlayerSelfCommandResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SelfRequestBuilderUriTemplate = "{+baseurl}/api/player/self";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SelfRequestBuilderNavigationMetadata: Record<Exclude<keyof SelfRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    username: {
        requestsMetadata: UsernameRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SelfRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SelfRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetPlayerDetailsSelfQueryResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SelfRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePlayerSelfCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
