import { Component } from '@angular/core';

import { SharedModule } from 'src/app/theme/shared/shared.module';

import { StockTableComponent } from 'src/app/components/stock-table/stock-table.component';
import { TemperatureSummaryComponent } from 'src/app/components/temperature-summary/temperature-summary.component';
import { PopupOverlayComponent } from "../../../components/popup-overlay/popup-overlay.component";
import { GameTableComponent } from "../../../components/progress-stocks-button/progress-stocks-button.component";
import { GameProgressResponse } from 'src/app/generated/autogenerated-client';
@Component({
  selector: 'app-devices',
  standalone: true,
  imports: [SharedModule, StockTableComponent, TemperatureSummaryComponent, PopupOverlayComponent, GameTableComponent],
  providers: [],
  templateUrl: './current-game.component.html',
  styleUrls: ['./current-game.component.scss']
})

export default class CurrentGameComponent {
  showPopup = false;
  progressionMessage:string = ""

  constructor() {
  }

  ngOnInit() {

  }

  handleProgressionEvent(gameEvent:GameProgressResponse){
    this.progressionMessage = gameEvent.newsMessage!;
    this.showPopup = true;
  }
}
