import { Component } from '@angular/core';

import { SharedModule } from 'src/app/theme/shared/shared.module';

import { StockTableComponent } from 'src/app/components/stock-table/stock-table.component';
import { TemperatureSummaryComponent } from 'src/app/components/temperature-summary/temperature-summary.component';
import { PopupOverlayComponent } from "../../../components/popup-overlay/popup-overlay.component";
import { GameTableComponent } from "../../../components/progress-stocks-button/progress-stocks-button.component";
import { GameProgressResponse } from 'src/app/generated/autogenerated-client';
@Component({
  selector: 'app-devices',
  standalone: true,
  imports: [SharedModule, StockTableComponent, TemperatureSummaryComponent, PopupOverlayComponent, GameTableComponent],
  providers: [],
  templateUrl: './current-game.component.html',
  styleUrls: ['./current-game.component.scss']
})

export default class CurrentGameComponent {
  showPopup = false;
  stockChanges:string[] = []
  progressionMessage:string = ""

  constructor() {
  }

  ngOnInit() {

  }

  handleProgressionEvent(gameEvent:GameProgressResponse):void{
    this.progressionMessage = gameEvent.newsMessage!;

    let newStockChanges = gameEvent.game?.stocks?.map(s => {
      if(s.lastPriceChange !== 0){
        return "<p>Stock <b>" + s.assetName + "<b/> has changed <b>"+ s.lastPriceChange +"<b/> !</p>";
      }
      return null;
    }).filter(change => change !== null);

    this.stockChanges = newStockChanges || [];

    this.showPopup = true;
  }
}
