import { InjectionToken } from '@angular/core';

/**
 * Base URL for the RegardedStonks API, resolved from runtime config at bootstrap.
 * Kept separate from generated/autogenerated-client.ts so regenerating the NSwag
 * client (`yarn generate:client`) never clobbers this token.
 */
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');
