<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <OpenApiFile>TGC.RegardedStonks.Api.json</OpenApiFile>
        <buildAngularClient>true</buildAngularClient>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.7" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\TGC.Framework\src\Communication\TGC.Communication\TGC.Communication\TGC.Communication.csproj" />
        <ProjectReference Include="..\TGC.RegardedStonks.Application\TGC.RegardedStonks.Application.csproj" />
        <ProjectReference Include="..\TGC.RegardedStonks.Infrastructure\TGC.RegardedStonks.Infrastructure.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
        <OpenApiDocumentsDirectory>$(ProjectDir)openapi</OpenApiDocumentsDirectory>
    </PropertyGroup>

    <Target Name="Kiota" Condition="'$(buildAngularClient)' == 'true'" AfterTargets="Build">
        <Exec Command="kiota generate --openapi $(ProjectDir)openapi/$(OpenApiFile) --language typescript --output ./../../TGC.RegardedStonks.App/src/app/auto_generated/client --exclude-backward-compatible"  />
    </Target>
</Project>
