/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetMatchInvitationsQueryResponeFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type GetMatchInvitationsQueryRespone, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/player/{-id}/invitations
 */
export interface InvitationsRequestBuilder extends BaseRequestBuilder<InvitationsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetMatchInvitationsQueryRespone>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<InvitationsRequestBuilderGetQueryParameters> | undefined) : Promise<GetMatchInvitationsQueryRespone | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<InvitationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface InvitationsRequestBuilderGetQueryParameters {
    matchId?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const InvitationsRequestBuilderUriTemplate = "{+baseurl}/api/player/{%2Did}/invitations{?matchId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const InvitationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetMatchInvitationsQueryResponeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
