import { Component } from '@angular/core';
import { GameClient, GameResponse } from 'src/app/generated/autogenerated-client';
import { CurrentGameState } from 'src/app/services/CurrentGameState.service';
import { SharedModule } from 'src/app/theme/shared/shared.module';

@Component({
  selector: 'app-progress-stocks-button',
  imports: [SharedModule],
  templateUrl: './progress-stocks-button.component.html',
  styleUrl: './progress-stocks-button.component.scss',
  providers: [GameClient],
  standalone: true
})
export class GameTableComponent {

  private currentGameId:string;

  constructor(private gameClient:GameClient, private currentGameStateService:CurrentGameState){
    this.currentGameId = currentGameStateService.getGameId();
  }

  public allGames:GameResponse[] | undefined;

  progressStocks():void{
    var currentGameId = this.currentGameStateService.getGameId();
    this.gameClient.progressGame(currentGameId).subscribe(response => {
      console.log("game progressed!")
      this.currentGameStateService.emitProgressEvent(response.game!);
    })
  }
}
