/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreatePlayerCommandResponseFromDiscriminatorValue, createGetAllPlayersQueryResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreatePlayerCommandResponse, serializeCreatePlayerRequest, type CreatePlayerCommandResponse, type CreatePlayerRequest, type GetAllPlayersQueryResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { PlayersItemRequestBuilderRequestsMetadata, type PlayersItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/players
 */
export interface PlayersRequestBuilder extends BaseRequestBuilder<PlayersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.admin.players.item collection
     * @param id Unique identifier of the item
     * @returns {PlayersItemRequestBuilder}
     */
     byId(id: Guid) : PlayersItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetAllPlayersQueryResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetAllPlayersQueryResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePlayerCommandResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     post(body: CreatePlayerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePlayerCommandResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePlayerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlayersRequestBuilderUriTemplate = "{+baseurl}/api/admin/players";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PlayersRequestBuilderNavigationMetadata: Record<Exclude<keyof PlayersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PlayersItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PlayersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetAllPlayersQueryResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePlayerCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePlayerRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
