/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetMatchInvitationsQueryResponeFromDiscriminatorValue, createInvitePlayerToMatchCommandResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreateMatchInvitationRequest, serializeInvitePlayerToMatchCommandResponse, type CreateMatchInvitationRequest, type GetMatchInvitationsQueryRespone, type InvitePlayerToMatchCommandResponse, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type WithInvitationItemRequestBuilder, WithInvitationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/matches/{-id}/invitations
 */
export interface InvitationsRequestBuilder extends BaseRequestBuilder<InvitationsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.matches.item.invitations.item collection
     * @param invitationId Unique identifier of the item
     * @returns {WithInvitationItemRequestBuilder}
     */
     byInvitationId(invitationId: Guid) : WithInvitationItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetMatchInvitationsQueryRespone>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetMatchInvitationsQueryRespone | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvitePlayerToMatchCommandResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 409 status code
     */
     post(body: CreateMatchInvitationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InvitePlayerToMatchCommandResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateMatchInvitationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InvitationsRequestBuilderUriTemplate = "{+baseurl}/api/matches/{%2Did}/invitations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InvitationsRequestBuilderNavigationMetadata: Record<Exclude<keyof InvitationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byInvitationId: {
        requestsMetadata: WithInvitationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["invitationId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InvitationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetMatchInvitationsQueryResponeFromDiscriminatorValue,
    },
    post: {
        uriTemplate: InvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvitePlayerToMatchCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateMatchInvitationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
