/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUpdateUsernameSelfCommandResponseFromDiscriminatorValue, serializeUpdateUsernameSelfCommandResponse, serializeUpdateUsernameSelfRequest, type ProblemDetails, type UpdateUsernameSelfCommandResponse, type UpdateUsernameSelfRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/player/self/username
 */
export interface UsernameRequestBuilder extends BaseRequestBuilder<UsernameRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UpdateUsernameSelfCommandResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 409 status code
     */
     put(body: UpdateUsernameSelfRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UpdateUsernameSelfCommandResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateUsernameSelfRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UsernameRequestBuilderUriTemplate = "{+baseurl}/api/player/self/username";
/**
 * Metadata for all the requests in the request builder.
 */
export const UsernameRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: UsernameRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUpdateUsernameSelfCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateUsernameSelfRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
