/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMatchCommandResponse}
 */
// @ts-ignore
export function createCreateMatchCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMatchCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMatchEventCommandResponse}
 */
// @ts-ignore
export function createCreateMatchEventCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMatchEventCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMatchEventRequest}
 */
// @ts-ignore
export function createCreateMatchEventRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMatchEventRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMatchInvitationRequest}
 */
// @ts-ignore
export function createCreateMatchInvitationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMatchInvitationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMatchRequest}
 */
// @ts-ignore
export function createCreateMatchRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMatchRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePlayerCommandResponse}
 */
// @ts-ignore
export function createCreatePlayerCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePlayerCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePlayerRequest}
 */
// @ts-ignore
export function createCreatePlayerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePlayerRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePlayerSelfCommandResponse}
 */
// @ts-ignore
export function createCreatePlayerSelfCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePlayerSelfCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetAllMatchesQueryResponse}
 */
// @ts-ignore
export function createGetAllMatchesQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetAllMatchesQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetAllPlayersQueryResponse}
 */
// @ts-ignore
export function createGetAllPlayersQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetAllPlayersQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetAvailableMatchesQueryResponse}
 */
// @ts-ignore
export function createGetAvailableMatchesQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetAvailableMatchesQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetMatchByIdQueryResponse}
 */
// @ts-ignore
export function createGetMatchByIdQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetMatchByIdQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetMatchInvitationsQueryRespone}
 */
// @ts-ignore
export function createGetMatchInvitationsQueryResponeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetMatchInvitationsQueryRespone;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetPlayerDetailsQueryResponse}
 */
// @ts-ignore
export function createGetPlayerDetailsQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetPlayerDetailsQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetPlayerDetailsSelfQueryResponse}
 */
// @ts-ignore
export function createGetPlayerDetailsSelfQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetPlayerDetailsSelfQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetPlayerRolesQueryResponse}
 */
// @ts-ignore
export function createGetPlayerRolesQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetPlayerRolesQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IMatchEventEntity}
 */
// @ts-ignore
export function createIMatchEventEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIMatchEventEntity;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IMatchInvitationEntity}
 */
// @ts-ignore
export function createIMatchInvitationEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIMatchInvitationEntity;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InvitePlayerToMatchCommandResponse}
 */
// @ts-ignore
export function createInvitePlayerToMatchCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInvitePlayerToMatchCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IPlayerEntity}
 */
// @ts-ignore
export function createIPlayerEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIPlayerEntity;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IPlayerPortfolio}
 */
// @ts-ignore
export function createIPlayerPortfolioFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIPlayerPortfolio;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IStockCompanyEntity}
 */
// @ts-ignore
export function createIStockCompanyEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIStockCompanyEntity;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IStockMatchEntity}
 */
// @ts-ignore
export function createIStockMatchEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIStockMatchEntity;
}
export interface CreateMatchCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CreateMatchEventCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CreateMatchEventRequest extends AdditionalDataHolder, Parsable {
    /**
     * The eventType property
     */
    eventType?: number | null;
    /**
     * The payload property
     */
    payload?: UntypedNode | null;
}
export interface CreateMatchInvitationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The playerId property
     */
    playerId?: Guid | null;
}
export interface CreateMatchRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The startingCapital property
     */
    startingCapital?: UntypedNode | null;
}
export interface CreatePlayerCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface CreatePlayerRequest extends AdditionalDataHolder, Parsable {
    /**
     * The oid property
     */
    oid?: Guid | null;
    /**
     * The userName property
     */
    userName?: string | null;
}
export interface CreatePlayerSelfCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateMatchInvitationRequest}
 */
// @ts-ignore
export function createUpdateMatchInvitationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateMatchInvitationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUsernameSelfCommandResponse}
 */
// @ts-ignore
export function createUpdateUsernameSelfCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUsernameSelfCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUsernameSelfRequest}
 */
// @ts-ignore
export function createUpdateUsernameSelfRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUsernameSelfRequest;
}
/**
 * The deserialization information for the current model
 * @param CreateMatchCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMatchCommandResponse(createMatchCommandResponse: Partial<CreateMatchCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createMatchCommandResponse.id = n.getGuidValue(); },
        "name": n => { createMatchCommandResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMatchEventCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMatchEventCommandResponse(createMatchEventCommandResponse: Partial<CreateMatchEventCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createMatchEventCommandResponse.id = n.getGuidValue(); },
        "name": n => { createMatchEventCommandResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMatchEventRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMatchEventRequest(createMatchEventRequest: Partial<CreateMatchEventRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "eventType": n => { createMatchEventRequest.eventType = n.getNumberValue(); },
        "payload": n => { createMatchEventRequest.payload = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMatchInvitationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMatchInvitationRequest(createMatchInvitationRequest: Partial<CreateMatchInvitationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "playerId": n => { createMatchInvitationRequest.playerId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMatchRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMatchRequest(createMatchRequest: Partial<CreateMatchRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createMatchRequest.name = n.getStringValue(); },
        "startingCapital": n => { createMatchRequest.startingCapital = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePlayerCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePlayerCommandResponse(createPlayerCommandResponse: Partial<CreatePlayerCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createPlayerCommandResponse.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePlayerRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePlayerRequest(createPlayerRequest: Partial<CreatePlayerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "oid": n => { createPlayerRequest.oid = n.getGuidValue(); },
        "userName": n => { createPlayerRequest.userName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePlayerSelfCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePlayerSelfCommandResponse(createPlayerSelfCommandResponse: Partial<CreatePlayerSelfCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createPlayerSelfCommandResponse.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetAllMatchesQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetAllMatchesQueryResponse(getAllMatchesQueryResponse: Partial<GetAllMatchesQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "matches": n => { getAllMatchesQueryResponse.matches = n.getCollectionOfObjectValues<IStockMatchEntity>(createIStockMatchEntityFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetAllPlayersQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetAllPlayersQueryResponse(getAllPlayersQueryResponse: Partial<GetAllPlayersQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "players": n => { getAllPlayersQueryResponse.players = n.getCollectionOfObjectValues<IPlayerEntity>(createIPlayerEntityFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetAvailableMatchesQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetAvailableMatchesQueryResponse(getAvailableMatchesQueryResponse: Partial<GetAvailableMatchesQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "companies": n => { getAvailableMatchesQueryResponse.companies = n.getCollectionOfObjectValues<IStockCompanyEntity>(createIStockCompanyEntityFromDiscriminatorValue); },
        "matches": n => { getAvailableMatchesQueryResponse.matches = n.getCollectionOfObjectValues<IStockMatchEntity>(createIStockMatchEntityFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetMatchByIdQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetMatchByIdQueryResponse(getMatchByIdQueryResponse: Partial<GetMatchByIdQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "match": n => { getMatchByIdQueryResponse.match = n.getObjectValue<IStockMatchEntity>(createIStockMatchEntityFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetMatchInvitationsQueryRespone The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetMatchInvitationsQueryRespone(getMatchInvitationsQueryRespone: Partial<GetMatchInvitationsQueryRespone> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "invitations": n => { getMatchInvitationsQueryRespone.invitations = n.getCollectionOfObjectValues<IMatchInvitationEntity>(createIMatchInvitationEntityFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetPlayerDetailsQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetPlayerDetailsQueryResponse(getPlayerDetailsQueryResponse: Partial<GetPlayerDetailsQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param GetPlayerDetailsSelfQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetPlayerDetailsSelfQueryResponse(getPlayerDetailsSelfQueryResponse: Partial<GetPlayerDetailsSelfQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { getPlayerDetailsSelfQueryResponse.active = n.getBooleanValue(); },
        "id": n => { getPlayerDetailsSelfQueryResponse.id = n.getGuidValue(); },
        "oid": n => { getPlayerDetailsSelfQueryResponse.oid = n.getGuidValue(); },
        "profilePicture": n => { getPlayerDetailsSelfQueryResponse.profilePicture = n.getStringValue(); },
        "username": n => { getPlayerDetailsSelfQueryResponse.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetPlayerRolesQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetPlayerRolesQueryResponse(getPlayerRolesQueryResponse: Partial<GetPlayerRolesQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "roles": n => { getPlayerRolesQueryResponse.roles = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IMatchEventEntity The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIMatchEventEntity(iMatchEventEntity: Partial<IMatchEventEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iMatchEventEntity.active = n.getBooleanValue(); },
        "created": n => { iMatchEventEntity.created = n.getDateValue(); },
        "createdBy": n => { iMatchEventEntity.createdBy = n.getGuidValue(); },
        "eventType": n => { iMatchEventEntity.eventType = n.getNumberValue(); },
        "id": n => { iMatchEventEntity.id = n.getGuidValue(); },
        "lastEdited": n => { iMatchEventEntity.lastEdited = n.getDateValue(); },
        "payload": n => { iMatchEventEntity.payload = n.getStringValue(); },
        "stockMatchId": n => { iMatchEventEntity.stockMatchId = n.getGuidValue(); },
        "updatedBy": n => { iMatchEventEntity.updatedBy = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IMatchInvitationEntity The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIMatchInvitationEntity(iMatchInvitationEntity: Partial<IMatchInvitationEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iMatchInvitationEntity.active = n.getBooleanValue(); },
        "authorId": n => { iMatchInvitationEntity.authorId = n.getGuidValue(); },
        "created": n => { iMatchInvitationEntity.created = n.getDateValue(); },
        "createdBy": n => { iMatchInvitationEntity.createdBy = n.getGuidValue(); },
        "id": n => { iMatchInvitationEntity.id = n.getGuidValue(); },
        "lastEdited": n => { iMatchInvitationEntity.lastEdited = n.getDateValue(); },
        "playerId": n => { iMatchInvitationEntity.playerId = n.getGuidValue(); },
        "status": n => { iMatchInvitationEntity.status = n.getNumberValue(); },
        "stockMatchId": n => { iMatchInvitationEntity.stockMatchId = n.getGuidValue(); },
        "updatedBy": n => { iMatchInvitationEntity.updatedBy = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InvitePlayerToMatchCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInvitePlayerToMatchCommandResponse(invitePlayerToMatchCommandResponse: Partial<InvitePlayerToMatchCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "invitationId": n => { invitePlayerToMatchCommandResponse.invitationId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IPlayerEntity The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIPlayerEntity(iPlayerEntity: Partial<IPlayerEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iPlayerEntity.active = n.getBooleanValue(); },
        "created": n => { iPlayerEntity.created = n.getDateValue(); },
        "createdBy": n => { iPlayerEntity.createdBy = n.getGuidValue(); },
        "id": n => { iPlayerEntity.id = n.getGuidValue(); },
        "lastEdited": n => { iPlayerEntity.lastEdited = n.getDateValue(); },
        "oid": n => { iPlayerEntity.oid = n.getGuidValue(); },
        "profilePicture": n => { iPlayerEntity.profilePicture = n.getStringValue(); },
        "updatedBy": n => { iPlayerEntity.updatedBy = n.getGuidValue(); },
        "username": n => { iPlayerEntity.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IPlayerPortfolio The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIPlayerPortfolio(iPlayerPortfolio: Partial<IPlayerPortfolio> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iPlayerPortfolio.active = n.getBooleanValue(); },
        "cash": n => { iPlayerPortfolio.cash = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "created": n => { iPlayerPortfolio.created = n.getDateValue(); },
        "createdBy": n => { iPlayerPortfolio.createdBy = n.getGuidValue(); },
        "id": n => { iPlayerPortfolio.id = n.getGuidValue(); },
        "lastEdited": n => { iPlayerPortfolio.lastEdited = n.getDateValue(); },
        "playerId": n => { iPlayerPortfolio.playerId = n.getGuidValue(); },
        "prisonReleaseAt": n => { iPlayerPortfolio.prisonReleaseAt = n.getDateValue(); },
        "status": n => { iPlayerPortfolio.status = n.getNumberValue(); },
        "stockMatchId": n => { iPlayerPortfolio.stockMatchId = n.getGuidValue(); },
        "updatedBy": n => { iPlayerPortfolio.updatedBy = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IStockCompanyEntity The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIStockCompanyEntity(iStockCompanyEntity: Partial<IStockCompanyEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iStockCompanyEntity.active = n.getBooleanValue(); },
        "availableStocks": n => { iStockCompanyEntity.availableStocks = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "bankrupt": n => { iStockCompanyEntity.bankrupt = n.getBooleanValue(); },
        "created": n => { iStockCompanyEntity.created = n.getDateValue(); },
        "createdBy": n => { iStockCompanyEntity.createdBy = n.getGuidValue(); },
        "description": n => { iStockCompanyEntity.description = n.getStringValue(); },
        "id": n => { iStockCompanyEntity.id = n.getGuidValue(); },
        "lastEdited": n => { iStockCompanyEntity.lastEdited = n.getDateValue(); },
        "lastReportedProfit": n => { iStockCompanyEntity.lastReportedProfit = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "lastReportedRevenue": n => { iStockCompanyEntity.lastReportedRevenue = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "liquidAssets": n => { iStockCompanyEntity.liquidAssets = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "longTermDebt": n => { iStockCompanyEntity.longTermDebt = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "name": n => { iStockCompanyEntity.name = n.getStringValue(); },
        "nonLiquidAssets": n => { iStockCompanyEntity.nonLiquidAssets = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "price": n => { iStockCompanyEntity.price = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "shortName": n => { iStockCompanyEntity.shortName = n.getStringValue(); },
        "shortTermDebt": n => { iStockCompanyEntity.shortTermDebt = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "stockMatchId": n => { iStockCompanyEntity.stockMatchId = n.getGuidValue(); },
        "totalStocks": n => { iStockCompanyEntity.totalStocks = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "updatedBy": n => { iStockCompanyEntity.updatedBy = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param IStockMatchEntity The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIStockMatchEntity(iStockMatchEntity: Partial<IStockMatchEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { iStockMatchEntity.active = n.getBooleanValue(); },
        "created": n => { iStockMatchEntity.created = n.getDateValue(); },
        "createdBy": n => { iStockMatchEntity.createdBy = n.getGuidValue(); },
        "endDateTime": n => { iStockMatchEntity.endDateTime = n.getDateValue(); },
        "id": n => { iStockMatchEntity.id = n.getGuidValue(); },
        "lastEdited": n => { iStockMatchEntity.lastEdited = n.getDateValue(); },
        "matchEvents": n => { iStockMatchEntity.matchEvents = n.getCollectionOfObjectValues<IMatchEventEntity>(createIMatchEventEntityFromDiscriminatorValue); },
        "name": n => { iStockMatchEntity.name = n.getStringValue(); },
        "playerPortfolios": n => { iStockMatchEntity.playerPortfolios = n.getCollectionOfObjectValues<IPlayerPortfolio>(createIPlayerPortfolioFromDiscriminatorValue); },
        "players": n => { iStockMatchEntity.players = n.getCollectionOfObjectValues<IPlayerEntity>(createIPlayerEntityFromDiscriminatorValue); },
        "startingCapital": n => { iStockMatchEntity.startingCapital = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "status": n => { iStockMatchEntity.status = n.getNumberValue(); },
        "stockCompanies": n => { iStockMatchEntity.stockCompanies = n.getCollectionOfObjectValues<IStockCompanyEntity>(createIStockCompanyEntityFromDiscriminatorValue); },
        "updatedBy": n => { iStockMatchEntity.updatedBy = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateMatchInvitationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateMatchInvitationRequest(updateMatchInvitationRequest: Partial<UpdateMatchInvitationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "status": n => { updateMatchInvitationRequest.status = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateUsernameSelfCommandResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUsernameSelfCommandResponse(updateUsernameSelfCommandResponse: Partial<UpdateUsernameSelfCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { updateUsernameSelfCommandResponse.id = n.getGuidValue(); },
        "username": n => { updateUsernameSelfCommandResponse.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateUsernameSelfRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUsernameSelfRequest(updateUsernameSelfRequest: Partial<UpdateUsernameSelfRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "username": n => { updateUsernameSelfRequest.username = n.getStringValue(); },
    }
}
export interface GetAllMatchesQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The matches property
     */
    matches?: IStockMatchEntity[] | null;
}
export interface GetAllPlayersQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The players property
     */
    players?: IPlayerEntity[] | null;
}
export interface GetAvailableMatchesQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The companies property
     */
    companies?: IStockCompanyEntity[] | null;
    /**
     * The matches property
     */
    matches?: IStockMatchEntity[] | null;
}
export interface GetMatchByIdQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The match property
     */
    match?: IStockMatchEntity | null;
}
export interface GetMatchInvitationsQueryRespone extends AdditionalDataHolder, Parsable {
    /**
     * The invitations property
     */
    invitations?: IMatchInvitationEntity[] | null;
}
export interface GetPlayerDetailsQueryResponse extends AdditionalDataHolder, Parsable {
}
export interface GetPlayerDetailsSelfQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The oid property
     */
    oid?: Guid | null;
    /**
     * The profilePicture property
     */
    profilePicture?: string | null;
    /**
     * The username property
     */
    username?: string | null;
}
export interface GetPlayerRolesQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The roles property
     */
    roles?: string[] | null;
}
export interface IMatchEventEntity extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The eventType property
     */
    eventType?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The payload property
     */
    payload?: string | null;
    /**
     * The stockMatchId property
     */
    stockMatchId?: Guid | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
}
export interface IMatchInvitationEntity extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The authorId property
     */
    authorId?: Guid | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The playerId property
     */
    playerId?: Guid | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The stockMatchId property
     */
    stockMatchId?: Guid | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
}
export interface InvitePlayerToMatchCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The invitationId property
     */
    invitationId?: Guid | null;
}
export interface IPlayerEntity extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The oid property
     */
    oid?: Guid | null;
    /**
     * The profilePicture property
     */
    profilePicture?: string | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
    /**
     * The username property
     */
    username?: string | null;
}
export interface IPlayerPortfolio extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The cash property
     */
    cash?: UntypedNode | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The playerId property
     */
    playerId?: Guid | null;
    /**
     * The prisonReleaseAt property
     */
    prisonReleaseAt?: Date | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The stockMatchId property
     */
    stockMatchId?: Guid | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
}
export interface IStockCompanyEntity extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The availableStocks property
     */
    availableStocks?: UntypedNode | null;
    /**
     * The bankrupt property
     */
    bankrupt?: boolean | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The lastReportedProfit property
     */
    lastReportedProfit?: UntypedNode | null;
    /**
     * The lastReportedRevenue property
     */
    lastReportedRevenue?: UntypedNode | null;
    /**
     * The liquidAssets property
     */
    liquidAssets?: UntypedNode | null;
    /**
     * The longTermDebt property
     */
    longTermDebt?: UntypedNode | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The nonLiquidAssets property
     */
    nonLiquidAssets?: UntypedNode | null;
    /**
     * The price property
     */
    price?: UntypedNode | null;
    /**
     * The shortName property
     */
    shortName?: string | null;
    /**
     * The shortTermDebt property
     */
    shortTermDebt?: UntypedNode | null;
    /**
     * The stockMatchId property
     */
    stockMatchId?: Guid | null;
    /**
     * The totalStocks property
     */
    totalStocks?: UntypedNode | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
}
export interface IStockMatchEntity extends AdditionalDataHolder, Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The created property
     */
    created?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: Guid | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lastEdited property
     */
    lastEdited?: Date | null;
    /**
     * The matchEvents property
     */
    matchEvents?: IMatchEventEntity[] | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The playerPortfolios property
     */
    playerPortfolios?: IPlayerPortfolio[] | null;
    /**
     * The players property
     */
    players?: IPlayerEntity[] | null;
    /**
     * The startingCapital property
     */
    startingCapital?: UntypedNode | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The stockCompanies property
     */
    stockCompanies?: IStockCompanyEntity[] | null;
    /**
     * The updatedBy property
     */
    updatedBy?: Guid | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: UntypedNode | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Serializes information the current object
 * @param CreateMatchCommandResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMatchCommandResponse(writer: SerializationWriter, createMatchCommandResponse: Partial<CreateMatchCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMatchCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", createMatchCommandResponse.id);
    writer.writeStringValue("name", createMatchCommandResponse.name);
    writer.writeAdditionalData(createMatchCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMatchEventCommandResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMatchEventCommandResponse(writer: SerializationWriter, createMatchEventCommandResponse: Partial<CreateMatchEventCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMatchEventCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", createMatchEventCommandResponse.id);
    writer.writeStringValue("name", createMatchEventCommandResponse.name);
    writer.writeAdditionalData(createMatchEventCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMatchEventRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMatchEventRequest(writer: SerializationWriter, createMatchEventRequest: Partial<CreateMatchEventRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMatchEventRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("eventType", createMatchEventRequest.eventType);
    writer.writeObjectValue("payload", createMatchEventRequest.payload);
    writer.writeAdditionalData(createMatchEventRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMatchInvitationRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMatchInvitationRequest(writer: SerializationWriter, createMatchInvitationRequest: Partial<CreateMatchInvitationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMatchInvitationRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("playerId", createMatchInvitationRequest.playerId);
    writer.writeAdditionalData(createMatchInvitationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMatchRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMatchRequest(writer: SerializationWriter, createMatchRequest: Partial<CreateMatchRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMatchRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createMatchRequest.name);
    writer.writeObjectValue("startingCapital", createMatchRequest.startingCapital);
    writer.writeAdditionalData(createMatchRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePlayerCommandResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePlayerCommandResponse(writer: SerializationWriter, createPlayerCommandResponse: Partial<CreatePlayerCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPlayerCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", createPlayerCommandResponse.id);
    writer.writeAdditionalData(createPlayerCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePlayerRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePlayerRequest(writer: SerializationWriter, createPlayerRequest: Partial<CreatePlayerRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPlayerRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("oid", createPlayerRequest.oid);
    writer.writeStringValue("userName", createPlayerRequest.userName);
    writer.writeAdditionalData(createPlayerRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePlayerSelfCommandResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePlayerSelfCommandResponse(writer: SerializationWriter, createPlayerSelfCommandResponse: Partial<CreatePlayerSelfCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPlayerSelfCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", createPlayerSelfCommandResponse.id);
    writer.writeAdditionalData(createPlayerSelfCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetAllMatchesQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetAllMatchesQueryResponse(writer: SerializationWriter, getAllMatchesQueryResponse: Partial<GetAllMatchesQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getAllMatchesQueryResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<IStockMatchEntity>("matches", getAllMatchesQueryResponse.matches, serializeIStockMatchEntity);
    writer.writeAdditionalData(getAllMatchesQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetAllPlayersQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetAllPlayersQueryResponse(writer: SerializationWriter, getAllPlayersQueryResponse: Partial<GetAllPlayersQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getAllPlayersQueryResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<IPlayerEntity>("players", getAllPlayersQueryResponse.players, serializeIPlayerEntity);
    writer.writeAdditionalData(getAllPlayersQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetAvailableMatchesQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetAvailableMatchesQueryResponse(writer: SerializationWriter, getAvailableMatchesQueryResponse: Partial<GetAvailableMatchesQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getAvailableMatchesQueryResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<IStockCompanyEntity>("companies", getAvailableMatchesQueryResponse.companies, serializeIStockCompanyEntity);
    writer.writeCollectionOfObjectValues<IStockMatchEntity>("matches", getAvailableMatchesQueryResponse.matches, serializeIStockMatchEntity);
    writer.writeAdditionalData(getAvailableMatchesQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetMatchByIdQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetMatchByIdQueryResponse(writer: SerializationWriter, getMatchByIdQueryResponse: Partial<GetMatchByIdQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getMatchByIdQueryResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<IStockMatchEntity>("match", getMatchByIdQueryResponse.match, serializeIStockMatchEntity);
    writer.writeAdditionalData(getMatchByIdQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetMatchInvitationsQueryRespone The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetMatchInvitationsQueryRespone(writer: SerializationWriter, getMatchInvitationsQueryRespone: Partial<GetMatchInvitationsQueryRespone> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getMatchInvitationsQueryRespone || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<IMatchInvitationEntity>("invitations", getMatchInvitationsQueryRespone.invitations, serializeIMatchInvitationEntity);
    writer.writeAdditionalData(getMatchInvitationsQueryRespone.additionalData);
}
/**
 * Serializes information the current object
 * @param GetPlayerDetailsQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetPlayerDetailsQueryResponse(writer: SerializationWriter, getPlayerDetailsQueryResponse: Partial<GetPlayerDetailsQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getPlayerDetailsQueryResponse || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(getPlayerDetailsQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetPlayerDetailsSelfQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetPlayerDetailsSelfQueryResponse(writer: SerializationWriter, getPlayerDetailsSelfQueryResponse: Partial<GetPlayerDetailsSelfQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getPlayerDetailsSelfQueryResponse || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", getPlayerDetailsSelfQueryResponse.active);
    writer.writeGuidValue("id", getPlayerDetailsSelfQueryResponse.id);
    writer.writeGuidValue("oid", getPlayerDetailsSelfQueryResponse.oid);
    writer.writeStringValue("profilePicture", getPlayerDetailsSelfQueryResponse.profilePicture);
    writer.writeStringValue("username", getPlayerDetailsSelfQueryResponse.username);
    writer.writeAdditionalData(getPlayerDetailsSelfQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param GetPlayerRolesQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetPlayerRolesQueryResponse(writer: SerializationWriter, getPlayerRolesQueryResponse: Partial<GetPlayerRolesQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getPlayerRolesQueryResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("roles", getPlayerRolesQueryResponse.roles);
    writer.writeAdditionalData(getPlayerRolesQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param IMatchEventEntity The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIMatchEventEntity(writer: SerializationWriter, iMatchEventEntity: Partial<IMatchEventEntity> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iMatchEventEntity || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iMatchEventEntity.active);
    writer.writeDateValue("created", iMatchEventEntity.created);
    writer.writeGuidValue("createdBy", iMatchEventEntity.createdBy);
    writer.writeNumberValue("eventType", iMatchEventEntity.eventType);
    writer.writeGuidValue("id", iMatchEventEntity.id);
    writer.writeDateValue("lastEdited", iMatchEventEntity.lastEdited);
    writer.writeStringValue("payload", iMatchEventEntity.payload);
    writer.writeGuidValue("stockMatchId", iMatchEventEntity.stockMatchId);
    writer.writeGuidValue("updatedBy", iMatchEventEntity.updatedBy);
    writer.writeAdditionalData(iMatchEventEntity.additionalData);
}
/**
 * Serializes information the current object
 * @param IMatchInvitationEntity The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIMatchInvitationEntity(writer: SerializationWriter, iMatchInvitationEntity: Partial<IMatchInvitationEntity> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iMatchInvitationEntity || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iMatchInvitationEntity.active);
    writer.writeGuidValue("authorId", iMatchInvitationEntity.authorId);
    writer.writeDateValue("created", iMatchInvitationEntity.created);
    writer.writeGuidValue("createdBy", iMatchInvitationEntity.createdBy);
    writer.writeGuidValue("id", iMatchInvitationEntity.id);
    writer.writeDateValue("lastEdited", iMatchInvitationEntity.lastEdited);
    writer.writeGuidValue("playerId", iMatchInvitationEntity.playerId);
    writer.writeNumberValue("status", iMatchInvitationEntity.status);
    writer.writeGuidValue("stockMatchId", iMatchInvitationEntity.stockMatchId);
    writer.writeGuidValue("updatedBy", iMatchInvitationEntity.updatedBy);
    writer.writeAdditionalData(iMatchInvitationEntity.additionalData);
}
/**
 * Serializes information the current object
 * @param InvitePlayerToMatchCommandResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInvitePlayerToMatchCommandResponse(writer: SerializationWriter, invitePlayerToMatchCommandResponse: Partial<InvitePlayerToMatchCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!invitePlayerToMatchCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("invitationId", invitePlayerToMatchCommandResponse.invitationId);
    writer.writeAdditionalData(invitePlayerToMatchCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param IPlayerEntity The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIPlayerEntity(writer: SerializationWriter, iPlayerEntity: Partial<IPlayerEntity> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iPlayerEntity || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iPlayerEntity.active);
    writer.writeDateValue("created", iPlayerEntity.created);
    writer.writeGuidValue("createdBy", iPlayerEntity.createdBy);
    writer.writeGuidValue("id", iPlayerEntity.id);
    writer.writeDateValue("lastEdited", iPlayerEntity.lastEdited);
    writer.writeGuidValue("oid", iPlayerEntity.oid);
    writer.writeStringValue("profilePicture", iPlayerEntity.profilePicture);
    writer.writeGuidValue("updatedBy", iPlayerEntity.updatedBy);
    writer.writeStringValue("username", iPlayerEntity.username);
    writer.writeAdditionalData(iPlayerEntity.additionalData);
}
/**
 * Serializes information the current object
 * @param IPlayerPortfolio The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIPlayerPortfolio(writer: SerializationWriter, iPlayerPortfolio: Partial<IPlayerPortfolio> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iPlayerPortfolio || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iPlayerPortfolio.active);
    writer.writeObjectValue("cash", iPlayerPortfolio.cash);
    writer.writeDateValue("created", iPlayerPortfolio.created);
    writer.writeGuidValue("createdBy", iPlayerPortfolio.createdBy);
    writer.writeGuidValue("id", iPlayerPortfolio.id);
    writer.writeDateValue("lastEdited", iPlayerPortfolio.lastEdited);
    writer.writeGuidValue("playerId", iPlayerPortfolio.playerId);
    writer.writeDateValue("prisonReleaseAt", iPlayerPortfolio.prisonReleaseAt);
    writer.writeNumberValue("status", iPlayerPortfolio.status);
    writer.writeGuidValue("stockMatchId", iPlayerPortfolio.stockMatchId);
    writer.writeGuidValue("updatedBy", iPlayerPortfolio.updatedBy);
    writer.writeAdditionalData(iPlayerPortfolio.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param IStockCompanyEntity The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIStockCompanyEntity(writer: SerializationWriter, iStockCompanyEntity: Partial<IStockCompanyEntity> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iStockCompanyEntity || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iStockCompanyEntity.active);
    writer.writeObjectValue("availableStocks", iStockCompanyEntity.availableStocks);
    writer.writeBooleanValue("bankrupt", iStockCompanyEntity.bankrupt);
    writer.writeDateValue("created", iStockCompanyEntity.created);
    writer.writeGuidValue("createdBy", iStockCompanyEntity.createdBy);
    writer.writeStringValue("description", iStockCompanyEntity.description);
    writer.writeGuidValue("id", iStockCompanyEntity.id);
    writer.writeDateValue("lastEdited", iStockCompanyEntity.lastEdited);
    writer.writeObjectValue("lastReportedProfit", iStockCompanyEntity.lastReportedProfit);
    writer.writeObjectValue("lastReportedRevenue", iStockCompanyEntity.lastReportedRevenue);
    writer.writeObjectValue("liquidAssets", iStockCompanyEntity.liquidAssets);
    writer.writeObjectValue("longTermDebt", iStockCompanyEntity.longTermDebt);
    writer.writeStringValue("name", iStockCompanyEntity.name);
    writer.writeObjectValue("nonLiquidAssets", iStockCompanyEntity.nonLiquidAssets);
    writer.writeObjectValue("price", iStockCompanyEntity.price);
    writer.writeStringValue("shortName", iStockCompanyEntity.shortName);
    writer.writeObjectValue("shortTermDebt", iStockCompanyEntity.shortTermDebt);
    writer.writeGuidValue("stockMatchId", iStockCompanyEntity.stockMatchId);
    writer.writeObjectValue("totalStocks", iStockCompanyEntity.totalStocks);
    writer.writeGuidValue("updatedBy", iStockCompanyEntity.updatedBy);
    writer.writeAdditionalData(iStockCompanyEntity.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param IStockMatchEntity The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIStockMatchEntity(writer: SerializationWriter, iStockMatchEntity: Partial<IStockMatchEntity> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!iStockMatchEntity || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("active", iStockMatchEntity.active);
    writer.writeDateValue("created", iStockMatchEntity.created);
    writer.writeGuidValue("createdBy", iStockMatchEntity.createdBy);
    writer.writeDateValue("endDateTime", iStockMatchEntity.endDateTime);
    writer.writeGuidValue("id", iStockMatchEntity.id);
    writer.writeDateValue("lastEdited", iStockMatchEntity.lastEdited);
    writer.writeCollectionOfObjectValues<IMatchEventEntity>("matchEvents", iStockMatchEntity.matchEvents, serializeIMatchEventEntity);
    writer.writeStringValue("name", iStockMatchEntity.name);
    writer.writeCollectionOfObjectValues<IPlayerPortfolio>("playerPortfolios", iStockMatchEntity.playerPortfolios, serializeIPlayerPortfolio);
    writer.writeCollectionOfObjectValues<IPlayerEntity>("players", iStockMatchEntity.players, serializeIPlayerEntity);
    writer.writeObjectValue("startingCapital", iStockMatchEntity.startingCapital);
    writer.writeNumberValue("status", iStockMatchEntity.status);
    writer.writeCollectionOfObjectValues<IStockCompanyEntity>("stockCompanies", iStockMatchEntity.stockCompanies, serializeIStockCompanyEntity);
    writer.writeGuidValue("updatedBy", iStockMatchEntity.updatedBy);
    writer.writeAdditionalData(iStockMatchEntity.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeObjectValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateMatchInvitationRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateMatchInvitationRequest(writer: SerializationWriter, updateMatchInvitationRequest: Partial<UpdateMatchInvitationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateMatchInvitationRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("status", updateMatchInvitationRequest.status);
    writer.writeAdditionalData(updateMatchInvitationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateUsernameSelfCommandResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUsernameSelfCommandResponse(writer: SerializationWriter, updateUsernameSelfCommandResponse: Partial<UpdateUsernameSelfCommandResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateUsernameSelfCommandResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", updateUsernameSelfCommandResponse.id);
    writer.writeStringValue("username", updateUsernameSelfCommandResponse.username);
    writer.writeAdditionalData(updateUsernameSelfCommandResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateUsernameSelfRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUsernameSelfRequest(writer: SerializationWriter, updateUsernameSelfRequest: Partial<UpdateUsernameSelfRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateUsernameSelfRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("username", updateUsernameSelfRequest.username);
    writer.writeAdditionalData(updateUsernameSelfRequest.additionalData);
}
export interface UpdateMatchInvitationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The status property
     */
    status?: number | null;
}
export interface UpdateUsernameSelfCommandResponse extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The username property
     */
    username?: string | null;
}
export interface UpdateUsernameSelfRequest extends AdditionalDataHolder, Parsable {
    /**
     * The username property
     */
    username?: string | null;
}
/* tslint:enable */
/* eslint-enable */
