/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetPlayerRolesQueryResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type GetPlayerRolesQueryResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/player/roles
 */
export interface RolesRequestBuilder extends BaseRequestBuilder<RolesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetPlayerRolesQueryResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetPlayerRolesQueryResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RolesRequestBuilderUriTemplate = "{+baseurl}/api/player/roles";
/**
 * Metadata for all the requests in the request builder.
 */
export const RolesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RolesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetPlayerRolesQueryResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
