/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PlayerItemRequestBuilderRequestsMetadata, type PlayerItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RolesRequestBuilderRequestsMetadata, type RolesRequestBuilder } from './roles/index.js';
// @ts-ignore
import { SelfRequestBuilderNavigationMetadata, SelfRequestBuilderRequestsMetadata, type SelfRequestBuilder } from './self/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/player
 */
export interface PlayerRequestBuilder extends BaseRequestBuilder<PlayerRequestBuilder> {
    /**
     * The roles property
     */
    get roles(): RolesRequestBuilder;
    /**
     * The self property
     */
    get self(): SelfRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.player.item collection
     * @param id Unique identifier of the item
     * @returns {PlayerItemRequestBuilder}
     */
     byId(id: Guid) : PlayerItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PlayerRequestBuilderUriTemplate = "{+baseurl}/api/player";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PlayerRequestBuilderNavigationMetadata: Record<Exclude<keyof PlayerRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PlayerItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    roles: {
        requestsMetadata: RolesRequestBuilderRequestsMetadata,
    },
    self: {
        requestsMetadata: SelfRequestBuilderRequestsMetadata,
        navigationMetadata: SelfRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
