/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminRequestBuilderNavigationMetadata, type AdminRequestBuilder } from './admin/index.js';
// @ts-ignore
import { MatchesRequestBuilderNavigationMetadata, MatchesRequestBuilderRequestsMetadata, type MatchesRequestBuilder } from './matches/index.js';
// @ts-ignore
import { PlayerRequestBuilderNavigationMetadata, type PlayerRequestBuilder } from './player/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The admin property
     */
    get admin(): AdminRequestBuilder;
    /**
     * The matches property
     */
    get matches(): MatchesRequestBuilder;
    /**
     * The player property
     */
    get player(): PlayerRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    admin: {
        navigationMetadata: AdminRequestBuilderNavigationMetadata,
    },
    matches: {
        requestsMetadata: MatchesRequestBuilderRequestsMetadata,
        navigationMetadata: MatchesRequestBuilderNavigationMetadata,
    },
    player: {
        navigationMetadata: PlayerRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
